server:
  port: 8088

#  providers: http://localhost:8081,http://localhost:8082,http://localhost:8083
#  zkServer: localhost:2181
#  zkRoot: lizrpc
lizrpc:
  zk:
    server: localhost:2181
    root: lizrpc
  app:
    id: app1
    namespace: public
    env: dev
  consumer:
    retries: 2
    timeout: 1000
    grayRatio: 10
    faultLimit: 10
    halfOpenInitialDelay: 10000
    halfOpenDelay: 60000

lizregistry:
  servers: http://localhost:8484

app:
  id: lizrpc-consumer
#apollo:
#  cache-dir: /opt/data/
#  cluster: default
#  meta: http://localhost:8080 #http://kimmking.cn:8070
#  autoUpdateInjectedSpringProperties: true
#  bootstrap:
#    enabled: true
#    namespaces: lizrpc-consumer,application
#    eagerLoad:
#      enabled: false

a:
  aa1
b:
  bb2

logging:
  level:
    root: info
    cn.liz.lizrpc: info
