
### 获取8088用户信息
GET http://localhost:8088/?id=101

### 测试超时重试
GET http://localhost:8088/findTimeout/?timeout=1100

### 通过8081调用接口 修改超时
GET http://localhost:8082/setTimeoutPorts?timeoutPorts=8083,8094

### 通过8088调用接口 修改 grayRatio
GET http://localhost:8088/setGrayRatio/?grayRatio=50

### 查询配置
GET http://localhost:8081/meta

### 获取用户信息
POST http://localhost:8081/lizrpc
Content-Type: application/json

{
  "service": "cn.liz.lizrpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [100]
}

### 获取用户信息
POST http://localhost:8081/lizrpc
Content-Type: application/json

{
  "service": "cn.liz.lizrpc.demo.api.UserService",
  "methodSign": "findById@2_int_java.lang.String",
  "args": [100, "lwf"]
}


### 获取订单信息
POST http://localhost:8081/
Content-Type: application/json

{
 "service": "cn.liz.lizrpc.demo.api.OrderService",
  "methodSign": "findById",
  "args": [200]
}

### toString
POST http://localhost:8081/
Content-Type: application/json

{
  "service": "cn.liz.lizrpc.demo.api.UserService",
  "method": "toString",
  "args": []
}

### hashCode
POST http://localhost:8081/lizrpc
Content-Type: application/json

{
  "service": "cn.liz.lizrpc.demo.api.UserService",
  "method": "hashCode",
  "args": []
}