server:
  port: 8081

lizrpc:
#  zkServer: localhost:2181
#  zkRoot: lizrpc
  zk:
    server: localhost:2181
    root: lizrpc
  app:
    id: app1
    namespace: public
    env : dev
  provider:
#    metas: "{'dc':'bj','unit':'u001','gray':'false'}"
    metas:
      dc: bj
      gray: false
      unit: B001
      tc: 300

logging:
  level:
    root: info
    cn.liz.lizrpc: info

app:
  id: lizrpc-provider
apollo:
  cache-dir: /opt/data/
  cluster: default
  meta: http://localhost:8080 #http://kimmking.cn:8070
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: lizrpc-provider,application
    eagerLoad:
      enabled: false

a:
  a1
b:
  b1

timeoutPorts:
  8082,8094
