server:
  port: 8081

lizrpc:
  zkServer: localhost:2181
  zkRoot: lizrpc

app:
  id: app1
  namespace: public
  env : dev
  metas: "{'dc':'bj','unit':'u001','gray':'false'}"

logging:
  level:
    root: info
    cn.liz.lizrpc: info


